"""data1.3

Revision ID: 147807238f59
Revises: 409a78a0ac77
Create Date: 2024-08-06 22:44:21.945122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147807238f59'
down_revision = '409a78a0ac77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
