"""Add autoincrement to user_id

Revision ID: 3c3bee8c5abc
Revises: df1f985d4540
Create Date: 2024-08-05 11:06:33.110208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3bee8c5abc'
down_revision = 'df1f985d4540'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
