"""Recreate missing migration

Revision ID: 3ea365600b63
Revises: 
Create Date: 2024-08-05 10:28:53.603261

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3ea365600b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.add_column('users', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'user_id')
    op.create_table('comments',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], name='comments_movie_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='comments_pkey')
                    )
    # ### end Alembic commands ###
