"""data1.2

Revision ID: 409a78a0ac77
Revises: c482e1454966
Create Date: 2024-08-06 22:33:36.415632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409a78a0ac77'
down_revision = 'c482e1454966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.drop_column('actors', 'year')
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'year')
    op.add_column('actors', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('actors', 'birth_year')
    # ### end Alembic commands ###
