"""data1.6

Revision ID: 87262d5ec930
Revises: 7968891fd219
Create Date: 2024-08-06 23:40:26.638001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87262d5ec930'
down_revision = '7968891fd219'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
