"""comments added 1.1

Revision ID: c322abcc5605
Revises: 0d63ce69d7d6
Create Date: 2024-08-05 15:52:05.276778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c322abcc5605'
down_revision = '0d63ce69d7d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
