"""data1.1

Revision ID: c482e1454966
Revises: 0b75103acd15
Create Date: 2024-08-06 22:29:05.884750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c482e1454966'
down_revision = '0b75103acd15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('actors', sa.Column('country', sa.String(), nullable=True))
    op.drop_index('ix_actors_gender', table_name='actors')
    op.create_index(op.f('ix_actors_actor_id'), 'actors', ['actor_id'], unique=False)
    op.drop_column('actors', 'gender')
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_genres_genre_id'), 'genres', ['genre_id'], unique=False)
    op.add_column('movies', sa.Column('release_date', sa.Integer(), nullable=True))
    op.drop_index('ix_movies_author', table_name='movies')
    op.drop_index('ix_movies_description', table_name='movies')
    op.drop_index('ix_movies_year', table_name='movies')
    op.create_index(op.f('ix_movies_movie_id'), 'movies', ['movie_id'], unique=False)
    op.drop_column('movies', 'year')
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.add_column('movies', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_movies_movie_id'), table_name='movies')
    op.create_index('ix_movies_year', 'movies', ['year'], unique=False)
    op.create_index('ix_movies_description', 'movies', ['description'], unique=False)
    op.create_index('ix_movies_author', 'movies', ['author'], unique=False)
    op.drop_column('movies', 'release_date')
    op.drop_index(op.f('ix_genres_genre_id'), table_name='genres')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.add_column('actors', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_actors_actor_id'), table_name='actors')
    op.create_index('ix_actors_gender', 'actors', ['gender'], unique=False)
    op.drop_column('actors', 'country')
    op.drop_column('actors', 'year')
    # ### end Alembic commands ###
