"""data1.0

Revision ID: dd4aefec3998
Revises: a743a7228b58
Create Date: 2024-08-06 17:25:07.302171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4aefec3998'
down_revision = 'a743a7228b58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
